[build]
builder = "nixpacks"
buildDir = "backend"

[deploy]
numReplicas = 1
restartThresholdType = "error"
restartThreshold = 5

[[services]]
name = "dgip-backend"
region = "eu-west"
healthcheckPath = "/"
healthcheckTimeout = 30
restart = true